"""Создание тестовой миграции 2

Revision ID: 60b102e3ca80
Revises: c4c10d0fcff5
Create Date: 2025-12-12 21:03:16.207825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60b102e3ca80'
down_revision: Union[str, None] = 'c4c10d0fcff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test2_id'), 'test2', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test2_id'), table_name='test2')
    op.drop_table('test2')
    # ### end Alembic commands ###

