"""Создание текстовой таблицы

Revision ID: 8e3633d4cc37
Revises: 2e02c8a05dda
Create Date: 2025-12-12 20:45:05.097237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3633d4cc37'
down_revision: Union[str, None] = '2e02c8a05dda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

